### ISSUE TITLE
Use the requests library for all the requests.

### ISSUE THREAD

**Issue by SanketDG** [harshasrinivas/clipy-github#14]
[`requests`](http://docs.python-requests.org/en/latest/) is pretty popular. Please take a moment to understand its advantages, some of it being having a RESTful api and cross version compatibility, so you don't need to use `future`.

More information here: http://stackoverflow.com/a/14804320/3578554

I could submit a pull request replacing `urllib` with `requests`, if this is okay with you.

**Comment by sananth12** [comment]
@SanketDG isn't future added here for py2/3 compatibility? Also, adding requests seems like a good idea, but IMO I don't think it's worth adding a dependency; as in this case, performance gains are not much.

**Comment by SanketDG** [comment]
@sananth12 
I meant that urllib's api is different for Python2 and Python3.
Requests has got a much cleaner api and is used extensively, also a cleaner syntax. When this library goes into authentication and stuff, then requests is really going to come in handy. But that's okay if it's way too trivial.

**Comment by SanketDG** [comment]
@sananth12 @harshasrinivas Any interest on moving this forward?

**Comment by harshasrinivas** [comment]
I agree with @sananth12. 
And by the way @SanketDG , future is added here for Python 2-3 compatibility, _not only for_ `urllib`.

**Comment by SanketDG** [comment]
@harshasrinivas
Sorry for my bad choice of words, but I didn't mean anything about future at all, what I meant was the differences in `urllib`'s api for py2 and py3 and using `requests` really has a lot of advantages. I don't know why adding a dependency could be a big deal, plus `urllib` is pretty limited.

**Comment by harshasrinivas** [comment]
Alright @SanketDG, lets go with `requests`. You can send me a pull.

**Comment by sananth12** [comment]
:+1: Seems good to me.

**Comment by SanketDG** [comment]
@harshasrinivas @sananth12 Really sorry for all of this confusion, but upon further inspection of the code, I have finally realized its way too trivial, given the current size of the codebase. `urllib` is more suited as of now.
Once again, sorry. Closing this.
