### ISSUE TITLE
cli-github -n does not work

### ISSUE THREAD

**Issue by robbyoconnor** [harshasrinivas/clipy-github#15]
I was unable to get cli-github -n to work...

```
$ cli-github -n robbyoconnor
Enter a valid URL. For help, type 'cli-github -h'
```

**Comment by robbyoconnor** [comment]
``
$ cli-github -n robbyoconnor
Enter a valid URL. For help, type 'cli-github -h'
```

**Comment by harshasrinivas** [comment]
works for me http://showterm.io/8ae054d6849335c6e75b8
That bug was fixed a few days back. But I just updated the [pip](https://pypi.python.org/pypi/cli-github/1.0.9) package. So try reinstalling again. It should work
