### ISSUE TITLE
Don't need metadata for rst files

### ISSUE THREAD

**Issue by SanketDG** [harshasrinivas/clipy-github#16]
The project currently uses two readme files, a `README.md` and a `README.rst`. We dont need both.
To allow the project description to be displayed in the pypi project page, we would only need one of them. If we use, `README.md` we need to add it to `[metadata]` in `setup.cfg`, but if we use ReST, we wouldn't need any `[metadata]`.

**Comment by SanketDG** [comment]
You still have two readme files.

**Comment by sananth12** [comment]
Just add README.rst to .gitignore

**Comment by SanketDG** [comment]
I think that a better option would be to use README.rst and remove README.md. If you prefer Markdown, just delete README.rst and insert a `[metadata]` line.
