### ISSUE TITLE
Use pypandoc to eliminate need of README.rst

### ISSUE THREAD

**Issue by iCHAIT** [harshasrinivas/clipy-github#20]
@harshasrinivas  Hi, I was wondering if README.rst could be removed from the source if  [pypandoc](https://pypi.python.org/pypi/pypandoc/) is used?

Something like this in `setup.py` - 

``` python
try:
    import pypandoc
    long_description = pypandoc.convert('Readme.md', 'rst')
except(IOError, ImportError):
    long_description = open('Readme.md').read()
```

Will this work?

**Comment by harshasrinivas** [comment]
I've tried it already but unfortunately, I had some formatting issues with [PyPI's documentation page](https://pypi.python.org/pypi/cli-github). :smile:

**Comment by iCHAIT** [comment]
Oh okay :)
