### ISSUE TITLE
not able to auth

### ISSUE THREAD

**Issue by ghost** [harshasrinivas/clipy-github#8]
```
➜  ~  cli-github -n sindhus
------------------------------------------------------------------------------------------------------------------------------------------------------
Invalid Credentials. For help, type 'clipy-github -h'
------------------------------------------------------------------------------------------------------------------------------------------------------
➜  ~  source ~/.zshrc
git_cmd=git
➜  ~  echo $GITHUB_TOKEN
<redacted>
➜  ~  cli-github -n sindhus
------------------------------------------------------------------------------------------------------------------------------------------------------
Invalid Credentials. For help, type 'clipy-github -h'
------------------------------------------------------------------------------------------------------------------------------------------------------
➜  ~  clipy-github -h
zsh: command not found: clipy-github
```

Am pretty sure I've set the the GITHUB_TOKEN env var and what's `clipy-github -h`? shouldn't it be `cli-github -h`?

What am I missing here with regards to credentials here that I can't use your module?
Thanks.

**Comment by harshasrinivas** [comment]
`clipy-github` was just a typo, and it's fixed now.
Regarding the token, please make sure that these two things are properly setup
- `GITHUB_TOKEN is set as <token-in-quotes>`
-  Go to the [token settings](https://github.com/settings/tokens) link and click `edit` to make sure that the scopes of your token are properly set up.

**Comment by ghost** [comment]
What are the scopes this program needs access to?

**Comment by ghost** [comment]
Auth works now. I think it would be more clear if you wrote in the README.md `export GITHUB_TOKEN="replace_this_with_your_token_leave_the_quotes". Thanks.

**Comment by harshasrinivas** [comment]
Sure. Will make it look clean in the next update
