### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by iCHAIT** [harshasrinivas/clipy-github#9]
I installed it using pip as mentioned and consequently tried running it but it gave me an error "INVALID CREDENTIALS", I am sorry but am I missing something?

Here is the screenshot for a quick look -

http://cl.ly/image/303K1g3N1s1n

**Comment by SanketDG** [comment]
Did you follow through the Setting Up section in the Readme. If yes, then type `echo $GITHUB_TOKEN` and it should print your key.

**Comment by iCHAIT** [comment]
Yeah, working for me now, it was not working on fish, i turned to bash and it is running fine. Thanks a lot for the quick response. :+1:

**Comment by SanketDG** [comment]
Fish probably has a different method for setting up environment variables.

**Comment by iCHAIT** [comment]
Yep, exactly. BTW, you may want to take fish into account as well (as far as the README of the project is concerned), just for the sake of completeness. Never mind, nice work :smiley:

**Comment by harshasrinivas** [comment]
Sure, @iCHAIT . Noted. It shall be made compatible with fish as well in the future updates!
And thanks @SanketDG for helping him out.
